Looknfeel
felixDev22/Leaderboard1 pull request #5
Opened 2022-12-23 20:29 UTC by felixDev22

**In this repo**

- [ ] Create a new branch
- [ ]  Added styling in CSS to create a look and feel of the "race car game"
- [ ] Maintained the wireframe and functionalities

2022-12-23 21:26 UTC, PinkMoon25 requested changes
Hi @felixDev22 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
linter checks :heavy_check_mark: 
Good commits :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Removing the Microverse logo from the Readme, you can add your own logo if you have one otherwise just use the project;s name, It will be more professional and personalised to your projects.
- Please consider adding the steps such as Install and usage instruction in your readme so anybody who visits this project can easily install and run it locally
![image](https://user-images.githubusercontent.com/97521557/209406671-9bbc1fcd-ca5d-49c0-a4cf-0e2a668cfb58.png)

- Please remove this tech stack and replace with the ones used in the project please see :point_down: 
![image](https://user-images.githubusercontent.com/97521557/209406765-e4edefbe-2d71-4efa-93b4-718198dc6581.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 21:26 UTC, PinkMoon25 commented on src/style.css
> +  background: url(./images/Car-Race2.png);
- [ ] Good job with the final touches, I think you accidentally used incorrect name for your image file and currently no styles are applied and we are getting this error :point_down: 
![image](https://user-images.githubusercontent.com/97521557/209406382-98da8962-5504-43fb-baca-fb4520f74137.png)

Please fix your image file name and make sure the webpack compiles the stylesheet successfully :+1:

2022-12-24 02:04 UTC, franclobo requested changes
Hi @felixDev22, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Correct Git flow ✔️ 
- Descriptive PR ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

- **As the last code reviewer said:** 👇🏽
- [x] Please 🙏🏽 remove the Microverse logo from the Readme file and add your own logo if you have one otherwise just use the project;s name, It will be more professional and personalized to your projects.

> Removing the Microverse logo from the Readme, you can add your own logo if you have one otherwise just use the project's name, It will be more professional and personalized to your projects.

- [x] Kindly add the instructions that allow a common user to use your application.

> Please consider adding the steps such as Install and usage instructions in your readme so anybody who visits this project can easily install and run it locally

![image](https://user-images.githubusercontent.com/58642949/209417385-79eb21ae-faf6-46a6-9b41-1cfb7979dfd3.png)

- [ ] Please 🙏🏽 replace the tech stack with the ones used in the project.

> Please remove this tech stack and replace it with the ones used in the project please see 👇

![image](https://user-images.githubusercontent.com/58642949/209417469-756668bd-e41d-4bfc-8f11-e71481cc9e69.png) 👇

![image](https://user-images.githubusercontent.com/58642949/209417454-8c691883-b7a3-4a45-a1f0-de1728aaaead.png)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-24 05:44 UTC, felixDev22 commented
Thank you - I have implemented the readme

2022-12-24 05:56 UTC, christianbiring1 approved these changes
Hi @felixDev22 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![imageswelljob](https://user-images.githubusercontent.com/97100091/209423479-b1af1c71-6cee-4284-bb95-1ab1f96c315f.jpeg)

## Highlights
- [ ] No linter errors :heavy_check_mark: 
- [ ] Correct Git flow :heavy_check_mark:
- [ ] Descriptive PR :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-24 05:57 UTC, merged